### ISSUE TITLE
Baulk 4.0 Roadmap

### ISSUE THREAD

**Issue by fcharlie** [baulk/baulk#36]
Although baulk is a very portable package management tool, it does not mean that baulk cannot go further. Baulk 4.0 will be a very interesting version, and there may be many changes. If you want to add any features to baulk, please feel free to suggest it. 

- [x] Better **VFS** design
- [x] Windows 11 context menu support
- [x] More C++20/23 experience
- [x] Better file extraction experience 
- [x] Limited compatibility with scoop manifest (?) 
- [x] More powerful bucket management and mirroring mechanism
- [x] baulk breakpoint download support
- [x] Integrate a better memory allocator, such as mimalloc
- [x] baulk brand command

**Comment by ChungZH** [comment]
👍

**Comment by fcharlie** [comment]
https://github.com/baulk/baulk/blob/dev-4.0/docs/zh-CN/baulk-4.0.md

https://github.com/baulk/baulk/tree/dev-4.0

**Comment by fcharlie** [comment]
https://zhuanlan.zhihu.com/p/402835148

**Comment by fcharlie** [comment]
## Progress for baulk brand

![image](https://user-images.githubusercontent.com/6904176/141683849-6276bbfe-3421-4e5a-8e96-ea188740b663.png)

![image](https://user-images.githubusercontent.com/6904176/141683898-d026ccda-e328-4e33-b770-da08884b9e60.png)

**Comment by fcharlie** [comment]
https://github.com/microsoft/vscode/pull/139640/files
